extends: ../../_base_/lidc/diagonal.yaml

experiment:
  name: dfm_diagonal_lidc_2class
  output_dir: /home/igarashi_25/DFM/results/diagonal_lidc

wandb:
  name: dfm-diagonal-lidc-2class
  tags: [lidc, 2-class, diagonal, full-resolution-state]
