extends: joint_simplex_b1_ce_smoothed_target_p08_160k.yaml

experiment:
  name: joint_simplex_b1_ce_smoothed_target_p08_ignore_void_160k
  output_dir: /home/igarashi_25/DFM/results/cityscapes/joint_simplex_b1_ce_smoothed_target_p08_ignore_void_160k

loss:
  consistency:
    psd:
      ignore_void: true

wandb:
  name: joint-simplex-b1-ce-smoothed-target-p08-ignore-void-160k
  tags:
    [cityscapes, joint, psd, simplex-source, source-ce,
     smoothed-target, p08, ignore-void, 160k]
