extends: joint_swin_t_segformer_b1_standard_ce_160k.yaml

experiment:
  name: dfm_joint_psd_cityscapes_swin_t_b1_bounded_gaussian_160k
  output_dir: /home/igarashi_25/DFM/results/cityscapes/joint_psd_cityscapes_swin_t_b1_bounded_gaussian_160k

source:
  prior_type: image_bounded_gaussian
  fixed_std: 1.0
  learned_logvar: false
  bounded_gaussian:
    amplitude: 1.0
    temperature: 5.0

flow:
  target_smoothing:
    enabled: false
    p: 0.0
  path:
    type: power
    exponent: 1.0

wandb:
  name: dfm-joint-psd-cityscapes-swin-t-b1-bounded-gaussian-160k
