extends: joint_bounded_gaussian_b1_150ep_source_then_trainable.yaml
experiment:
  name: dfm_original_cityscapes_b1_exponential_path_trainable_800ep
  output_dir: /home/igarashi_25/DFM/results/cityscapes/original/b1_exponential_path_trainable_800ep
flow:
  path:
    type: entropy_adaptive
    entropy: {normalization: rank, exclude_ignore: false, exclude_predicted_void: false}
    scheduler: {type: exponential, beta: 2.0, difficulty_gamma: 1.0}
