extends: joint_bounded_gaussian_b1_exponential_path_trainable.yaml

experiment:
  name: dfm_original_cityscapes_b1_exponential_path_trainable_stage2_from_epoch0150_650ep
  output_dir: /home/igarashi_25/DFM/results/cityscapes/original/b1_exponential_path_trainable_stage2_from_epoch0150_650ep

checkpoint:
  init_from: /home/igarashi_25/DFM/results/cityscapes/original/b1_exponential_path_adaptive_std_trainable_800ep/epoch_0150.pt

source:
  supervision:
    weight_schedule:
      start_epoch: 0
      duration: 50

training:
  epochs: 650
  stages:
    enabled: true
    source_pretrain: {enabled: false}
    flow_training: {enabled: true, start_epoch: 0, end_epoch: 650, train_source: true, train_flow: true}
  flow_weight_schedule:
    start_epoch: 0
