extends: joint_bounded_gaussian_b1_exponential_path_adaptive_std_trainable.yaml
experiment:
  name: dfm_original_cityscapes_b1_exponential_path_adaptive_std_frozen_800ep
  output_dir: /home/igarashi_25/DFM/results/cityscapes/original/b1_exponential_path_adaptive_std_frozen_800ep
training:
  stages:
    flow_training: {train_source: false}
