extends: ../../_base_/ade20k/joint_psd.yaml

model:
  image_encoder:
    type: swin
    variant: tiny
    pretrained: true
    freeze: false
    input_already_normalized: true
    neck:
      type: ddp_fpn_merge
      channels: 256
