# configs/lidc/psd/segformer_source_no_align_joint.yaml

extends: ../../_base_/lidc/joint_psd.yaml

experiment:
  name: dfm_joint_psd_lidc_no_align
  output_dir: /home/igarashi_25/DFM/results/lidc/segformer_source_no_align_psd

source:
  use_loss_align: false
  align_weight: 0.0
  supervision:
    type: align
    weight: 0.0

wandb:
  name: dfm-lidc-segformer-source-psd